### ISSUE TITLE
TODO : features && bugs

### ISSUE THREAD

**Issue by HsingPeng** [openthos/printer-analysis#28]
#1 features
### HIGH
- [x] （网络打印1/6）openthos作服务端，win客户端打印
- [x] （网络打印2/6）openthos作服务端，ubuntu客户端打印
- [x] （网络打印3/6）win作服务端，openthos客户端打印
- [x] （网络打印4/6）ubuntu作服务端，openthos客户端打印
- [x] （网络打印5/6）openthos作服务端，openthos客户端打印
- [x] （网络打印6/6）自带网络功能的打印机作服务端，openthos客户端打印
- [x] 完善打印参数（指定彩色/黑白）
- [x] 页边距设置功能（WPS等编辑软件已有该功能）
- [x] 打印页码选择功能
- [x] 打印机设置功能
- [x] 打印任务管理功能
- [x] CancelPrintTask   C3  取消打印功能
### MIDDLE
- [x] 添加hpcups/hplip驱动（主要支持hp喷墨打印机）
- [x] 正确关闭cups程序（解决CUPS不及时存储数据的问题）
- [x] 打印机高级设置，各项微调
- [x] 插入打印机自动提示
### LOW
- [x] 自动选择打印机驱动
- [x] 扩充纸张大小参数MediaSize对应项
- [x] 调节打印管理界面布局
### CUPS不支持
- [x] ~~双面打印~~（指定无效）
- [x] ~~缺纸提示~~ 
### 暂不需要
- [x] ~~添加ROOT模式运行（脚本：chown current_id:current_id all_files）~~
- [x] ~~判断系统平台，以提示驱动是否可用~~
- [x] ~~使用strip缩减程序体积~~
- [x] ~~自动判断是否已勾选打印服务插件~~
- [x] ~~在程序中写个使用帮助，告知用户打印流程~~
#2 bugs
### HIGH
- [x] 打印任务不及时更新
- [x] 打印机调整配置页面点击确定后打印服务崩溃
- [ ] 有些ppd无法正确解析到设置
- [x] 打印任务状态显示unknown
- [x] 打印任务从暂停状态恢复失败
- [x] 修复tar解压文件部分权限丢失
- [x] 去除奔图ppd文件名中的空格
### MIDDLE
- [x] 修复打印管理界面偶尔错乱BUG
- [x] 添加本地/网络打印机字段为空判断（也不能有空格）
  ### LOW
### 暂不需要
- [x] ~~在其他系统上不能检测某些USB打印机~~
- [x] ~~初始化成功不刷新列表（缺省应该没有打印机）~~
#3 other
- [x] foo2oak等驱动测试
- [ ] 给openprinting贡献打印机测试情况
- [x] 调查网络打印是否可用
- [x] 收集驱动色彩键值
- [x] 编写脚本根据文件owner权限批量修改文件后两个权限（解决无法打开web管理界面问题）
